name: Ubuntu - Test
on: [push, pull_request]
jobs:
  ubuntu-test:
    name: Ubuntu - Test
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Install Crystal libs
        run: shards install
      - name: wfc-cr post-install
        run: sh ./rsrc/install.sh
      - name: crystal spec
        run: crystal spec